[workspace]
authors = ["Peter Alexander <makeroftools@creativedevelopment.systems>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "coinbase-app"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.0,<3.15"
requests = ">=2.32.5,<3"
cryptography = ">=46.0.3,<47"
pyjwt = ">=2.10.1,<3"
websockets = ">=15.0.1,<16"
backoff = ">=2.2.1,<3"
